#!/bin/bash

function linkfile () {
  srcfile=$1
  dotfile=$2
  echo -n $dotfile -\> dotfiles/$srcfile \
    && [[ ! -e $dotfile ]] \
    && ln -s dotfiles/$srcfile $dotfile \
    && echo " [ok]" \
    || echo " [exists]"
}

cd $HOME

if [ ! -d dotfiles ]; then
  echo "No 'dotfiles' directory found!"
  exit 1
fi

source dotfiles/install.config

for f in dotfiles/*; do
  if [[ $f == *.md || $f == *install* || $f == .* ]]; then
    continue
  fi
  fn=$(basename $f)
  ln=.$fn
  if [[ $no_dot == *$fn* ]]; then
    ln=$fn
  fi
  linkfile $fn $ln
done

